### ISSUE TITLE
Estimator

### ISSUE THREAD

**Issue by katesaikishore** [RubixML/Sentiment#2]
I am seeing the estimator file system is with the .model formate how to make .model file? I want to rank the data where the doc's says
$scores = $estimator->rank($dataset);

var_dump($scores);
but $estimator should be given how?

**Comment by andrewdalpino** [comment]
Hi @katesaikishore 

The estimator used in this project/tutorial is a classifier - only anomaly detectors implement the [Ranking](https://docs.rubixml.com/en/latest/ranking.html) interface. Maybe you are looking for [Probabilities](https://docs.rubixml.com/en/latest/probabilistic.html) instead?

I recommend reading the tutorial for an example on how the estimator is instantiated. A `.model` file is created when an estimator instance is saved/persisted.

If part of the documentation is not clear, let me know and I will work to clarify it

Thanks!

**Comment by katesaikishore** [comment]
Thanks Understood.

**Comment by andrewdalpino** [comment]
Were you able to get it working @katesaikishore?

**Comment by katesaikishore** [comment]
yes it works! :)

**Comment by andrewdalpino** [comment]
Great

Were there some parts of the tutorial that could be improved/made more clear?

**Comment by katesaikishore** [comment]
Yeah please create a project on ranking system like you have done for context emotion detection. It will be really helpful.
